version: '1.0'
stages:
  - clone
  - package
  - build
  - deploy
steps:
  main_clone:
    title: Cloning spring-boot repo
    stage: clone
    type: git-clone
    repo: 'balu1862/spring-boot-test-app'
    revision: master
    git: github
  create_package:
    title: creating the jar file
    stage: package
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package   
  image_build:
    title: Building Docker Image
    type: build
    stage: build
    image_name: balu2143/spring-boot-test-app
    working_directory: ./
    dockerfile: Dockerfile
  deploy_to_cluster:
    title: Deploying in GKE
    type: deploy
    stage: deploy
    kind: kubernetes  
    cluster:  gke-cluster
    namespace: default
    file_path: ./deployment.yml
    registry: codefresh-docker-registry
