apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: spring-boot
        image: balu2143/spring-boot-2-sample-app:main
        ports:
        - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
